name: Artifact

on:
  workflow_dispatch:
  pull_request:
    types: [opened, reopened]
    branches: [master, main]

jobs:
  artifact:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install Node
        uses: actions/setup-node@v3
        with:
          node-version: '16.15.1'
      - name: Get Info
        run: |
          echo "id=$(jq -r '.id' plugin.json)" >> $GITHUB_OUTPUT
          echo "version=$(jq -r '.version' plugin.json)" >> $GITHUB_OUTPUT
        id: info
      - name: Install Webapp Dependencies
        uses: borales/actions-yarn@v4
        with:
          cmd: install
          dir: '${{ github.workspace }}/webapp'
      - name: Build Artifact
        run: |
          cd ${{ github.workspace }} && make
      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: ${{ steps.info.outputs.id }}-${{ steps.info.outputs.version }}
          path: dist/${{ steps.info.outputs.id }}-${{ steps.info.outputs.version }}.tar.gz
