name: Release

on:
  push:
    branches: [master, main]

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
      - name: Install Node
        uses: actions/setup-node@v3
        with:
          node-version: '16.15.1'
      - name: Get Info
        run: |
          echo "id=$(jq -r '.id' plugin.json)" >> $GITHUB_OUTPUT
          echo "version=$(jq -r '.version' plugin.json)" >> $GITHUB_OUTPUT
        id: info
      - name: Generate Changelog
        run: |
          awk '/## [0-9]/{p++} p; /## [0-9]/{if (p > 1) exit}' CHANGELOG.md | awk 'NR>2 {print last} {last=$0}' > RELEASE.md
      - name: Install Webapp Dependencies
        uses: borales/actions-yarn@v4
        with:
          cmd: install
          dir: '${{ github.workspace }}/webapp'
      - name: Build Artifact
        run: |
          cd ${{ github.workspace }} && make
      - name: Create Release
        uses: ncipollo/release-action@v1
        id: create_release
        with:
          artifacts: "./dist/${{ steps.info.outputs.id }}-${{ steps.info.outputs.version }}.tar.gz"
          bodyFile: RELEASE.md
          tag: v${{ steps.info.outputs.version }}
